package com.example.data.api

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiClient {
    private const val TAG = "GeminiClient"
    private val JSON_MEDIA_TYPE = "application/json; charset=utf-8".toMediaType()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    /**
     * Standard text content generation.
     */
    suspend fun generateContent(prompt: String, systemInstruction: String? = null, forceJson: Boolean = false): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isNullOrEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.w(TAG, "API Key is empty or placeholder! Please configure it in the Secrets panel.")
            return@withContext "ERROR_KEY_MISSING"
        }

        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"

        try {
            val root = JSONObject()
            
            val contentsArray = JSONArray()
            val contentObj = JSONObject()
            val partsArray = JSONArray()
            val partObj = JSONObject()
            partObj.put("text", prompt)
            partsArray.put(partObj)
            contentObj.put("parts", partsArray)
            contentsArray.put(contentObj)
            root.put("contents", contentsArray)

            if (systemInstruction != null) {
                val sysInstObj = JSONObject()
                val sysPartsArray = JSONArray()
                val sysPartObj = JSONObject()
                sysPartObj.put("text", systemInstruction)
                sysPartsArray.put(sysPartObj)
                sysInstObj.put("parts", sysPartsArray)
                root.put("systemInstruction", sysInstObj)
            }

            if (forceJson) {
                val config = JSONObject()
                val respFormat = JSONObject()
                respFormat.put("responseMimeType", "application/json")
                config.put("responseFormat", respFormat)
                root.put("generationConfig", config)
            }

            val requestBody = root.toString().toRequestBody(JSON_MEDIA_TYPE)
            val request = Request.Builder()
                .url(url)
                .post(requestBody)
                .build()

            okHttpClient.newCall(request).execute().use { response ->
                val responseBody = response.body?.string()
                if (!response.isSuccessful) {
                    Log.e(TAG, "API Error: Code ${response.code}, Body: $responseBody")
                    return@withContext "Error: API returned code ${response.code}"
                }

                if (responseBody == null) {
                    return@withContext "Error: Empty response body."
                }

                val jsonResponse = JSONObject(responseBody)
                val candidates = jsonResponse.optJSONArray("candidates")
                val firstCandidate = candidates?.optJSONObject(0)
                val content = firstCandidate?.optJSONObject("content")
                val parts = content?.optJSONArray("parts")
                val text = parts?.optJSONObject(0)?.optString("text")

                text ?: "Error: No text generated by Gemini."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Exception during content generation", e)
            "Error: ${e.localizedMessage ?: "Unknown connection error"}"
        }
    }

    /**
     * Generates a structural JSON response containing local SEO analysis.
     */
    suspend fun generateSeoAudit(
        businessName: String,
        category: String,
        location: String,
        keywords: List<String>
    ): String {
        val keywordsString = keywords.joinToString(", ")
        val systemInstruction = """
            You are a professional Local SEO Audit and Maps Ranking engineer.
            Analyze the business's details and generate a JSON response with recommendations to rank #1 on Google Maps.
            The JSON response MUST strictly follow this exact schema:
            {
              "score": <int, e.g. 78>,
              "gmbCompleteness": <int, e.g. 85>,
              "citationCount": <int, e.g. 14>,
              "critical_issues": ["Issue 1", "Issue 2", ...],
              "opportunities": ["Opportunity 1", "Opportunity 2", ...],
              "citation_health": "A summary of NAP consistency and directories found."
            }
            Do not wrap in triple backticks or markdown markers, output ONLY the pure JSON object.
        """.trimIndent()

        val prompt = """
            Analyze this local business:
            - Name: $businessName
            - Category: $category
            - Location: $location
            - Target Map Keywords: $keywordsString

            Determine realistic critical issues preventing them from ranking in the local 3-pack on Google Maps, actionable opportunities to optimize, and compute a ranking score.
        """.trimIndent()

        return generateContent(prompt, systemInstruction, forceJson = true)
    }

    /**
     * Generates a personalized reply to a Google Maps review.
     */
    suspend fun generateReviewReply(
        businessName: String,
        reviewerName: String,
        rating: Int,
        reviewText: String,
        replyTone: String
    ): String {
        val systemInstruction = """
            You are the owner of the local business '$businessName'.
            Your task is to write a highly localized, helpful, and natural response to a customer review on Google Maps.
            Tailor your tone to the user's selected style: '$replyTone'.
            Keep it professional, engaging, and compact (2-3 sentences max).
            If the review is negative (1-3 stars), be empathetic, offer an apology, and provide a polite way for them to contact you directly off-line to resolve it.
            Do not use generic corporate language; make it sound authentic and personalized to the reviewer '$reviewerName'.
        """.trimIndent()

        val prompt = """
            Write a Google Maps reply to:
            - Reviewer: $reviewerName
            - Rating: $rating/5 Stars
            - Review Comment: "$reviewText"
            - Desired Tone: $replyTone
        """.trimIndent()

        return generateContent(prompt, systemInstruction, forceJson = false)
    }

    /**
     * Generates an SEO GMB Post or Promotional Campaign Update.
     */
    suspend fun generateGmbPost(
        businessName: String,
        topic: String,
        callToAction: String
    ): String {
        val prompt = """
            Write a highly engaging Google Business Profile (formerly GMB) post for '$businessName'.
            Topic of Post: "$topic"
            Call to Action: "$callToAction"
            
            Keep the post under 150 words. Write in a lively local tone. Include 2-3 localized hashtags.
            Structure it with:
            1. An eye-catching headline
            2. High-value details
            3. A clear Call to Action (e.g. "Tap 'Learn More' below to reserve yours!")
        """.trimIndent()

        return generateContent(prompt, "You are a local business GMB copywriting specialist.", forceJson = false)
    }
}
